---
version: "3.7"

services:
  frontend:
    build:
      context: ./
      dockerfile: tools/docker/frontend/Dockerfile
  web-server:
    build:
      context: ./
      dockerfile: tools/docker/web-server/Dockerfile
    ports:
      - 80:80
    networks:
      - web_frontend
    volumes:
      - type: tmpfs
        target: /var/cache/nginx
      - type: tmpfs
        target: /var/run/nginx
    expose:
      - 9000
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: ./
      dockerfile: ./tools/docker/php-fpm/Dockerfile
    environment:
      SYMFONY_CACHE_DIR: /site/cache
      SYMFONY_LOGS_DIR: /site/logs
    volumes:
      - type: tmpfs
        target: /site/cache
      - code:/site/code:ro
      - ./logs:/site/logs
    networks:
      - web_frontend
    dns:
      - 8.8.8.8
      - 8.8.4.4
    expose:
      - 9000
  base-php:
    build:
      context: ./
      dockerfile: ./tools/docker/php/Dockerfile
    image: shrikeh/php7.4-base:latest
  app:
    build:
      context: ./
      dockerfile: tools/docker/app/Dockerfile
    environment:
      APP_ENV:
      APP_DEBUG:
      SYMFONY_CACHE_DIR: /cache
      SYMFONY_LOGS_DIR: /logs
    volumes:
      - type: tmpfs
        target: /cache
      - code:/code:ro
      - ./logs:/site/logs
networks:
  web_frontend:
volumes:
  code:
  logs:
