---
version: "3.7"

services:
  frontend:
    build:
      context: ./
      dockerfile: ./tools/docker/frontend/Dockerfile
    ports:
      - 80:80
    networks:
      - web_frontend
    volumes:
      - type: tmpfs
        target: /var/cache/nginx
      - type: tmpfs
        target: /var/run/nginx
  rabbitmq:
    image: rabbitmq:3.8.1
    expose:
      - 5672
    networks:
      - amqp_consumers
      - amqp_senders
  base-php:
    build:
      context: ./
      dockerfile: ./tools/docker/php/Dockerfile
    image: shrikeh/php7.4-base:latest
  app:
    build:
      context: ./
      dockerfile: tools/docker/app/Dockerfile
    environment:
      APP_ENV:
      APP_DEBUG:
      SYMFONY_CACHE_DIR: /cache
      MESSENGER_TRANSPORT_DSN: 'amqp://guest:guest@rabbitmq:5672/%2f/messages'
    volumes:
      - type: tmpfs
        target: /cache
    networks:
      - amqp_senders
  consumer:
    build:
      context: ./
      dockerfile: tools/docker/consumer/Dockerfile
    environment:
      APP_ENV:
      APP_DEBUG:
      SYMFONY_CACHE_DIR: /cache
      MESSENGER_TRANSPORT_DSN: 'amqp://guest:guest@rabbitmq:5672/%2f/messages'
    volumes:
      - type: tmpfs
        target: /cache
    networks:
      - amqp_consumers
networks:
  amqp_consumers:
  amqp_senders:
  web_frontend:
